### ISSUE TITLE
Builds fail on master

### ISSUE THREAD

**Issue by jonegard** [grafana/dashboard-spec#7]
Hello, I am interested in contributing to this project. When I attempted to run `go run . 7.0 jsonnet` on a newly cloned master the build unfortunately failed with the following error message `open _gen/7.0/spec.json: no such file or directory`. Are builds only intended to work on the `_gen` branch or is there an issue with the master branch?

**Comment by jonegard** [comment]
Perhaps @Brombeersaft or @trotttrotttrott know what the story is here? 🙂

**Comment by trotttrotttrott** [comment]
Hi @jonegard! Run `make bundle` to generate that file. Also, take a look at https://github.com/grafana/grafana/pull/28793. This will have some implications for this project, but we haven't made any moves yet.

**Comment by jonegard** [comment]
Hi @trotttrotttrott. I completely missed that step, thanks for getting back and letting me know about it. I'll close this issue now. 🙂
